# source: https://github.com/cpp-best-practices/cmake_template/blob/main/cmake/InterproceduralOptimization.cmake
macro(myproject_enable_ipo)
  include(CheckIPOSupported)
  check_ipo_supported(RESULT result OUTPUT output)
  if(result)
    message(STATUS "IPO supported: ${result}")
    set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
  else()
    message(SEND_ERROR "IPO is not supported: ${output}")
  endif()
endmacro()
